### ISSUE TITLE
死にまくっている。

### ISSUE THREAD

**Issue by nna774** [nna774/twitter-save#1]
```
 7月 13 03:30:25 sakura.nna774.net systemd[1]: ikaduchi.service failed.
 7月 13 03:30:28 sakura.nna774.net systemd[1]: ikaduchi.service holdoff time over, scheduling restart.
 7月 13 03:30:28 sakura.nna774.net systemd[1]: Started ikaduchi.
 7月 13 03:30:28 sakura.nna774.net systemd[1]: Starting ikaduchi...
 7月 13 03:32:11 sakura.nna774.net bash[27880]: /home/nona/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/twitter-5.16.0/lib/twitter/streaming/response.rb:21:in `on_headers_complete': Twitter:
 7月 13 03:32:11 sakura.nna774.net bash[27880]: from /home/nona/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/twitter-5.16.0/lib/twitter/streaming/response.rb:16:in `<<'
 7月 13 03:32:11 sakura.nna774.net bash[27880]: from /home/nona/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/twitter-5.16.0/lib/twitter/streaming/response.rb:16:in `<<'
 7月 13 03:32:11 sakura.nna774.net bash[27880]: from /home/nona/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/twitter-5.16.0/lib/twitter/streaming/connection.rb:22:in `stream'
 7月 13 03:32:11 sakura.nna774.net bash[27880]: from /home/nona/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/twitter-5.16.0/lib/twitter/streaming/client.rb:119:in `request'
 7月 13 03:32:11 sakura.nna774.net bash[27880]: from /home/nona/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/twitter-5.16.0/lib/twitter/streaming/client.rb:92:in `user'
 7月 13 03:32:11 sakura.nna774.net bash[27880]: from main.rb:140:in `<main>'
 7月 13 03:32:11 sakura.nna774.net systemd[1]: ikaduchi.service: main process exited, code=exited, status=1/FAILURE
 7月 13 03:32:11 sakura.nna774.net systemd[1]: Unit ikaduchi.service entered failed state.
 7月 13 03:32:11 sakura.nna774.net systemd[1]: ikaduchi.service failed.
```

```
 7月 13 03:30:25 sakura.nna774.net bash[27827]: /home/nona/.rbenv/versions/2.3.1/lib/ruby/2.3.0/openssl/buffering.rb:125:in `sysread': end of file reached (EOFError)
 7月 13 03:30:25 sakura.nna774.net bash[27827]: from /home/nona/.rbenv/versions/2.3.1/lib/ruby/2.3.0/openssl/buffering.rb:125:in `readpartial'
 7月 13 03:30:25 sakura.nna774.net bash[27827]: from /home/nona/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/twitter-5.16.0/lib/twitter/streaming/connection.rb:21:in `stream'
 7月 13 03:30:25 sakura.nna774.net bash[27827]: from /home/nona/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/twitter-5.16.0/lib/twitter/streaming/client.rb:119:in `request'
 7月 13 03:30:25 sakura.nna774.net bash[27827]: from /home/nona/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/twitter-5.16.0/lib/twitter/streaming/client.rb:92:in `user'
```

Twitterが調子悪いだけ？
ならいいけど……。

https://github.com/sferik/twitter/issues/535 こういうのが出てきた。

**Comment by nna774** [comment]
https://github.com/nna774/twitter-save/commit/425ef83184dbdae52ac5c375ff4fb597522b890f でひとまず対応とする。
